# Generated by Django 6.0.7 on 2026-07-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_creacion',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='activo',
            new_name='disponible',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='destacado',
            new_name='nuevo',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default='categoria', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
