# Generated by Django 6.0.7 on 2026-07-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_producto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='envio_gratis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='opiniones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
