# Generated by Django 5.0.14 on 2026-09-03 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_categoria_id_alter_producto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='catalogo.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='catalogo.talla')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de productos',
                'unique_together': {('producto', 'color', 'talla')},
            },
        ),
    ]
